### ISSUE TITLE
Firework Rockets

### ISSUE THREAD

**Issue by Janooary** [Linguardium/ItemNbtModels#2]
Hi, I'm trying to change the color of fireworks based on their flight duration for a resource pack but I can't seem to get my textures to appear. How would I go about calling the Flight NBT tag? Would I use "Nbt.Number('Flight') = 2" ?

**Comment by Linguardium** [comment]
proper javascript should use `==` to indicate a check not `=`
if the Integer NBT tag is in the root tag and the value is called `Flight`, then you are very close with the exception of the `=` rather than `==`

however, looking at proper NBT for Fireworks, they have the following NBT path:

```
{
    Fireworks {
         Byte Flight
    }
}
```
(along with some other nbt values, of course)

so it should be `Nbt.Number('Fireworks.Flight')` for flight time
